[package]
edition = "2024"
name = "happy-cracking"
version = "0.1.0"

[dependencies]
anyhow = "1.0.101"
base64 = "0.22.1"
bs58 = "0.5.1"
clap = {version = "4.5.57", features = ["derive"]}
data-encoding = "2.10.0"
hex = "0.4.3"
md-5 = "0.10.6"
sha1 = "0.10.6"
sha2 = "0.10.9"
num-bigint = "0.4.6"
num-integer = "0.1.46"
num-traits = "0.2.19"
urlencoding = "2.1.3"
